services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: api-football-test:prod
    container_name: api-app-prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    depends_on:
      redis:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: api-football-test:prod
    container_name: api-worker-prod
    command: npm run worker:prod
    env_file:
      - .env
    environment:
      NODE_ENV: production
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis-data:
